FROM node:16 as base

WORKDIR /app/lobby
COPY package.json .
COPY package-lock.json .
# Perform clean install rather than attempting to update
RUN npm ci

# Hardcode version for local development
ENV VERSION Local build

COPY . .

FROM node:16 as client

ENV VERSION Local build

WORKDIR /app

RUN git clone https://github.com/throneteki/throneteki-client.git

WORKDIR /app/throneteki-client

RUN npm install
RUN npm run build

FROM base as final

WORKDIR /app/lobby

COPY --from=client /app/throneteki-client/dist ./public
COPY --from=client /app/throneteki-client/assets ./public

CMD [ "npm", "start" ]