FROM node:16

RUN mkdir -p /app/node
WORKDIR /app/node

# Hardcode version for local development
ENV VERSION Local build

COPY package.json /app/node/
COPY package-lock.json /app/node/

# Perform clean install rather than attempting to update
RUN npm ci
COPY . /app/node

CMD [ "npm", "run", "gamenode" ]