FROM node:16

RUN mkdir -p /app/node
WORKDIR /app/node

COPY package.json .
COPY package-lock.json .

# Perform clean install rather than attempting to update
RUN npm ci

# Hardcode version for local development
ENV VERSION Local build

COPY . .

CMD [ "npm", "run", "gamenode" ]