apiVersion: v1
kind: Service
metadata:
    name: throneteki-lobby
    # prettier-ignore
    namespace: {{ .Values.namespace }}
spec:
    type: {{ default "ClusterIP" .Values.service.type }}
{{- $svcType := default "ClusterIP" .Values.service.type }}
{{- if or (eq $svcType "LoadBalancer") (eq $svcType "NodePort") }}
    externalTrafficPolicy: {{ default "Local" .Values.service.externalTrafficPolicy }}
{{- end }}
    selector:
        app: throneteki-lobby
    ports:
        - port: 80
          targetPort: 80
          protocol: TCP
