namespace: throneteki-development
environment: development

image:
    repository: cryogen/throneteki-lobby
    tag: latest

service:
    type: ClusterIP
    externalTrafficPolicy: Local

deployTime: '0'

nodeConfig: {}

storage:
    className: local-path
    cardImages: 5Gi
    avatars: 1Gi

resources: {}
