name: Deploy Lobby
on:
    workflow_dispatch:
        inputs:
            environment:
                type: environment
                description: Select the environment
                default: Production
jobs:
    deploy:
        runs-on: self-hosted
        environment: ${{ inputs.environment }}
        steps:
            - name: Pull latest lobby image
              run: docker pull cryogen/throneteki-lobby
            - name: Stop and remove lobby image
              continue-on-error: true
              run: docker stop ${{ vars.CONTAINER_NAME }} && docker rm ${{ vars.CONTAINER_NAME }}
            - name: Run new lobby image
              run: docker run --restart unless-stopped -d -p ${{ vars.LOBBY_PORT }}:80 --network ${{ vars.NETWORK_NAME }} -v ${{ vars.CARDS_PATH }}:/usr/src/app/public/img/cards -v ${{ vars.AVATAR_PATH }}:/usr/src/app/public/img/avatar -v ${{ vars.LOG_PATH }}:/usr/src/app/server/logs --name ${{ vars.CONTAINER_NAME }} --env DEBUG="monk:*, mongo:*" --env NODE_CONFIG='{"env":"production","sentryDsn":"${{ secrets.SENTRY_DSN }}","captchaKey":"${{ secrets.CAPTHCA_KEY }}","minLobbyChatTime":3600,"dbPath":"${{ secrets.DB_PATH }}","cookieLifetime":604800000,"redisUrl":"${{ secrets.REDIS_URL }}","secret":"${{ secrets.SECRET }}","emailKey":"${{ secrets.EMAIL_KEY }}","emailBlockKey":"${{ secrets.EMAIL_BLOCK_KEY }}","port":80,"hmacSecret":"${{ secrets.HMAC }}","requireActivation":false,"patreonCallbackUrl":"${{ vars.PATREON_CALLBACK_URL }}","patreonClientId":"${{ secrets.PATREON_CLIENTID }}","patreonSecret":"${{ secrets.PATREON_SECRET }}"}' cryogen/throneteki-lobby
